// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP7hNZ-VxDpvFNQYuaHuf9Iig050Fd8q8',
    appId: '1:1005510201091:web:b771e03f1f4578d89fe336',
    messagingSenderId: '1005510201091',
    projectId: 'flutterchatapp-67e59',
    authDomain: 'flutterchatapp-67e59.firebaseapp.com',
    storageBucket: 'flutterchatapp-67e59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZlmzQYQh8u0p0z7cnrl0CrJ4nRrIiAc',
    appId: '1:1005510201091:android:f05c7f66c2df3f8a9fe336',
    messagingSenderId: '1005510201091',
    projectId: 'flutterchatapp-67e59',
    storageBucket: 'flutterchatapp-67e59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBycIrCn6Z1VSuBp8vDUm2Sa_NKLly_O08',
    appId: '1:1005510201091:ios:8e54292776af9af49fe336',
    messagingSenderId: '1005510201091',
    projectId: 'flutterchatapp-67e59',
    storageBucket: 'flutterchatapp-67e59.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBycIrCn6Z1VSuBp8vDUm2Sa_NKLly_O08',
    appId: '1:1005510201091:ios:b4b8a147ef7476199fe336',
    messagingSenderId: '1005510201091',
    projectId: 'flutterchatapp-67e59',
    storageBucket: 'flutterchatapp-67e59.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
